### ISSUE TITLE
Kombilo closes instantly after opening on MacOS Mojave

### ISSUE THREAD

**Issue by aheavyburden** [ugoertz/kombilo#4]
I've obtained a MacOS version of Kombilo-84 from [here](https://www.u-go.net/kombilo/)

Where this is the download link listed on that page: 
https://dl.u-go.net/kombilo/kombilo-084.app.zip

I can extract Kombilo fine, but when I try to launch it, it just instantly closes.

Any ideas on how to fix this? I'm currently running the Windows Kombilo under Wine but would much rather have the native version.

Is there anything I need to do beforehand so that the MacOS version of Kombilo runs as it should?

**Comment by ugoertz** [comment]
Sorry for not replying earlier. Unfortunately I cannot really help with this since I do not have access to a Mac where I could try this myself. Maybe you could ask on lifein19x19.com.

**Comment by mekriff** [comment]
On version Ventura 13.4.1 using the M1 chip, I get a similar result (have for a few versions now),
I've also tried installing on terminal through python (2.7 seems to no longer be an option, so I've tried with 3.9.7 as another thread suggested it might work sometimes on 3.X python),
the result I get is 

> traceback (most recent call last):
>   File "/Users/USERNAME/.pyenv/versions/3.9.7/bin/kombilo", line 5, in <module>
>     from kombilo.kombilo import run
>   File "/Users/USERNAME/.pyenv/versions/3.9.7/lib/python3.9/site-packages/kombilo/kombilo.py", line 33, in <module>
>     from string import split, find, join, strip, replace
> ImportError: cannot import name 'split' from 'string' (/Users/USERNAME/.pyenv/versions/3.9.7/lib/python3.9/string.py)

I haven't poked through the libraries to figure it out, but I hope the information is at least partially helpful

**Comment by mekriff** [comment]
addendum: I copied over the master branch and tried to run kombilo.py, and got a different error of

> 
> Traceback (most recent call last):
>   File "/Users/USERNAME/Downloads/kombilo-master/kombilo/./kombilo.py", line 56, in <module>
>     from .tooltip.tooltip import ToolTip
> ImportError: attempted relative import with no known parent package
>
